# Generated by Django 4.1.3 on 2022-11-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='usename',
        ),
    ]
