# Generated by Django 4.1.3 on 2022-12-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('depName', models.CharField(max_length=100)),
                ('Clinic', models.CharField(max_length=120)),
                ('Degree', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('charge', models.IntegerField()),
                ('langauge', models.CharField(max_length=100)),
            ],
        ),
    ]
