# Generated by Django 4.1.3 on 2022-12-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_doctoraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoraccount',
            name='username',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
