# Generated by Django 4.1 on 2022-12-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rating'),
        ('home', '0020_health_bllod_2'),
    ]

    operations = [
    ]
