<<<<<<< HEAD
# Generated by Django 4.1 on 2022-12-13 07:12
=======
# Generated by Django 4.1.4 on 2022-12-22 14:13
>>>>>>> ec0decf4c99b40666db5361d45c290f3e7d31acc

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rating'),
        ('home', '0020_health_bllod_2'),
    ]

    operations = [
    ]
