# Generated by Django 4.1.4 on 2022-12-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rating'),
        ('home', '0020_health_bllod_2'),
    ]

    operations = [
    ]
